train_fraction: 0.8
random_state: 3
target_column: species

agg:
  group_columns:
    - species
  agg_columns:
    - sepal_width
    - petal_length
  agg_params:
    - mean
    - median

dashboards:
  pages:
    main:
      text: "This piece of text is paramerized over `conf/base/parameters.yaml`"
    view:
      transformation:
        duplicate_arg:
          "Sepal length": "sepal_length"
        rename_arg:
          "sepal_width": "Sepal width"
          "petal_width": "Petal Width"
          "petal_length": "Petal Length"
          "species": "Species"
        soft_upsert_arg:
          species: "unknown species"
          species_detail: "unknown species"
        fillna_arg:
          missing_col: default
        replace_arg:
          species:
            versicolor: "type #1"
            setosa: "type #2"
        drop_arg:
          - sepal_length


    iris_aggregation:
      agg_params:
        - mean
        - median
        - count
        - std
    edit:
      configure_pagination:
        enabled: True
      configure_side_bar:
        filters_panel: True
        columns_panel: True
        defaultToolPanel: ""
      configure_column:
        sepal_length:
          field: "sepal_length"
          editable: True
        sepal_width:
          field: "sepal_width"
          editable: True
        petal_length:
          field: "petal_length"
          editable: True
        petal_width:
          field: "petal_width"
          editable: True
        species:
          field: "species"
          editable: True
      AgGrid:
        columns_auto_size_mode: "FIT_CONTENTS"
        data_return_mode: AS_INPUT
        fit_columns_on_grid_load: True
        theme: streamlit
        enable_enterprise_modules: False
        width: "100%"
        reload_data: False
        editable: True
        allow_unsafe_jscode: True
